{
   "before_install" : "true",
   "env" : {
      "global" : {
         "secure" : "WPaJL3g77Yp30uvZpiQ0yYGpmXU9FKVeers46GyY/ZWeLQJG4yQroBo47NHBX3Hdal9LosrzoD1pPRyoXLNXMpQPdaYztcgUSZyp\u002BrQQj8agrTk6a\u002B1eiKZ\u002BVOUw4rK3s4kEo6g7JE4J9FOo2arjdC4t/y48C48wuuVRnlPP2oMLZR8MHBMSDWojHg9PxyuYzRDJ4a9TeZtYhOTvawKRmradcaII4nNIFdZKqzLx6t39C\u002BGC/1ysfJoxBRBaDXltVq2hKzmDWYImIgwzCGCvXmyGQZbE0VM5\u002BPKBh9eowOWpPbNfdjFhfrHdCIdfy46AZEH/GbnT1aqFz8trLU72YuGkp2ihHnA\u002BKX21Xd6bS80tBT79pd46VKDt5/kjwuFZP5wvKHytLW9DNDDnRhhOYdYO6RCYGpCNffpybxUIO8QAEivsIDXIxw7/3EOgkqokWHsGIFL6pwaDf2Yzf96VOGxhyrMg3utgq5PJdkQBy40mgP40We399zcrofoMOh4h8M\u002BwWq7pyhC1UQX9gR68ZFGvrpgITb15BLeTAhPqtn\u002B5jrNvuCpi/VZDfl42N0AP/v9NmwcEb8cBVEitl2KipW/ecNzzOYQv5aXaz2xK6pWbE8A2JzWLw9vqyJQfO8GbYtx1Gjcsx/7GmDHWbIk0HbzFSr2awIEGAEXSbVfqX\u002BQ=\u000A"
      }
   },
   "git" : {
      "submodules" : false
   },
   "install" : "make test-deps",
   "jobs" : {
      "include" : [
         {
            "stage" : "test"
         },
         {
            "before_install" : "true",
            "install" : "true",
            "script" : "curl -f https://gist.githubusercontent.com/wakaba/ab553f86cd017e0cb28c6dbb5364b009/raw/travis-merge-job.pl | perl",
            "stage" : "merge"
         }
      ]
   },
   "language" : "perl",
   "notifications" : {
      "email" : [
         "wakaba@suikawiki.org"
      ],
      "irc" : {
         "channels" : [
            "ircs://irc.suikawiki.org:6697#mechanize"
         ],
         "use_notice" : true
      }
   },
   "perl" : [
      "5.26"
   ],
   "script" : "make test"
}
